package com.example.topcoder.graph;

import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import static org.testng.Assert.*;

public class FriendScoreTest {

    private FriendScore friendScore;

    @BeforeMethod
    public void setup() {
        this.friendScore = new FriendScore();
    }

    @Test
    public void testHighestScore_Example0() throws Exception {
        //setup
        String[] friends =
                {"NNN",
                 "NNN",
                 "NNN"};

        //test
        int score = this.friendScore.highestScore(friends);

        //verify
        assertEquals(score, 0);
    }

    @Test
    public void testHighestScore_Example1() throws Exception {
        //setup
        String[] friends =
                {"NYY",
                 "YNY",
                 "YYN"};

        //test
        int score = this.friendScore.highestScore(friends);

        //verify
        assertEquals(score, 2);
    }

    @Test
    public void testHighestScore_Example2() throws Exception {
        //setup
        String[] friends =
                {"NYNNN",
                 "YNYNN",
                 "NYNYN",
                 "NNYNY",
                 "NNNYN"};

        //test
        int score = this.friendScore.highestScore(friends);

        //verify
        assertEquals(score, 4);
    }

    @Test
    public void testHighestScore_Example3() throws Exception {
        //setup
        String[] friends =
                       {"NNNNYNNNNN",
                        "NNNNYNYYNN",
                        "NNNYYYNNNN",
                        "NNYNNNNNNN",
                        "YYYNNNNNNY",
                        "NNYNNNNNYN",
                        "NYNNNNNYNN",
                        "NYNNNNYNNN",
                        "NNNNNYNNNN",
                        "NNNNYNNNNN"};

        //test
        int score = this.friendScore.highestScore(friends);

        //verify
        assertEquals(score, 8);
    }

    @Test
    public void testHighestScore_Example4() throws Exception {
        //setup
        String[] friends =
                       {"NNNNNNNNNNNNNNY",
                        "NNNNNNNNNNNNNNN",
                        "NNNNNNNYNNNNNNN",
                        "NNNNNNNYNNNNNNY",
                        "NNNNNNNNNNNNNNY",
                        "NNNNNNNNYNNNNNN",
                        "NNNNNNNNNNNNNNN",
                        "NNYYNNNNNNNNNNN",
                        "NNNNNYNNNNNYNNN",
                        "NNNNNNNNNNNNNNY",
                        "NNNNNNNNNNNNNNN",
                        "NNNNNNNNYNNNNNN",
                        "NNNNNNNNNNNNNNN",
                        "NNNNNNNNNNNNNNN",
                        "YNNYYNNNNYNNNNN"};

        //test
        int score = this.friendScore.highestScore(friends);

        //verify
        assertEquals(score, 6);
    }

    @Test
    public void testHighestScore_SystemTest0() throws Exception {
        //setup
        String[] friends =
                {"NNNNNNNNNNNNNNNNNNYNNNNYYYNNNNNNNNNNNNNNYN", "NNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNYNNNNNNYNN", "NNNNNNNNNNNNNNNNNYNNNYNNNNNNNNNNNNNNNNNNNY", "NNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNYNNNYNN", "NNNNNYYNNNNNYNNNNNNNNNNNYNNNNNNNNNNNNNNNNN", "NNNNYNNNNNNNNYNNNNYNNNNNNNNNNNNNYNNNNYYNNN", "NNNNYNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNYNN", "NNNNNNNNNNNNNNNNNNNNNNNYNYNYNYNNNNNNNNNNYN", "NNNNNNNNNNNNYNNNNNNNNYNNNYNNYNNNNNNNNYNNYN", "NNNNNNNNNNYNNNNNNNYNNNNNNNNNNYNNYYNYNNNNNN", "NNNNNNNNNYNNNNNNNNNNYNYNNNNNNNNNNYYNNNYNNN", "NNNNNNNNNNNNNNYNNNNNNNYNNNNNNNYNNNNNNNNNNN", "NNNNYNNNYNNNNNNYYNNNYNNNNNNNNYNNNNNNNNNNNN", "NNNNNYNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNY", "NNNNNNNNNNNYNNNYNNNNNNNNNNNNNYNNNYYYNNNYNN", "NYNNNNNNNNNNYNYNYNNNYNNNNNNNNNNNNYNNNNNNNN", "NNNNNNNNNNNNYNNYNNYNNNNNNNNNNNNNNNNNNNNNNN", "NNYNNNNNNNNNNNNNNNNNNNYNYNNNNNYNNNNYNYNNYN", "YNNNNYNNNYNNNNNNYNNNYNNYNYNNNNNNNYNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNYNN", "NNNNNNNNNNYNYNNYNNYNNYNNNNYNNNNNNNNYNNNNNN", "NNYNNNNNYNNNNNNNNNNNYNNNNNNNNNYYNYNNNNNNNN", "NNNNNNNNNNYYNNNNNYNNNNNNNNNNNYNNNNNNNNNNNN", "YNNNNNNYNNNNNNNNNNYNNNNNNNNNNNNNNYNNNNNNNN", "YNNNYNYNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNYYNN", "YNNNNNNYYNNNNNNNNNYNNNNNNNNNNYNNNNNYYNNNNN", "NNNYNNNNNNNNNNNNNNNNYNNNNNNNNYNNNNNNNNNNNN", "NNNNNNNYNNNNNNNNNNNNNNNNNNNNYNYYNNNNNNNNYN", "NNNNNNNNYNNNNNNNNNNNNNNNNNNYNNNNNNNNNNYNNN", "NNNNNNNYNYNNYYYNNNNNNNYNNYYNNNNNNNNNNNNNNN", "NNNNNNNNNNNYNNNNNYNNNYNNNNNYNNNNNNNNNNYNNY", "NNNNNNNNNNNNNNNNNNNNNYNNNNNYNNNNNNNYNNNNNN", "NYNNNYNNNYNNNNNNNNNNNNNNNNNNNNNNNNYNNNNYNN", "NNNNNNNNNYYNNNYYNNYNNYNYNNNNNNNNNNYNNNNNYN", "NNNNNNNNNNYNNNYNNNNNNNNNNNNNNNNNYYNNNNNNNY", "NNNYNNNNNYNNNNYNNYNYYNNNNYNNNNNYNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNN", "NNNNNYNNYNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNYNNNNYNNNNNNNNNNNNNYNNNYNYNNNNNNNNNYN", "NYNYNNYNNNNNNNYNNNNYNNNNYNNNNNNNYNNNNNNNNN", "YNNNNNNYYNNNNNNNNYNNNNNNNNNYNNNNNYNNNNYNNN", "NNYNNNNNNNNNNYNNNNNNNNNNNNNNNNYNNNYNNNNNNN"}	;

        //test
        int score = this.friendScore.highestScore(friends);

        //verify
        assertEquals(score, 31);
    }

    @Test
    public void testHighestScore_SystemTest1() throws Exception {
        //setup
        String[] friends =
                {"NNYYNNNYNNNNNNNNNYNNNYYNNYYNNYNNYNNYNNYYNNNN", "NNNNNNNNNYYNNNNNNNNNNNNNNNNNYYYNYNNNYNNNNNYN", "YNNYYNYYNYNNYYNNYNYNYNNYNNNNNNYYNYNNNYNNNNNN", "YNYNNNNNNYNNNNNNNNNNYNYNNNYYNNNNYNNNNNNNNNNN", "NNYNNYNYNNNNNYYYYNNNNNNNNYNNYNNNYNYNNNYNYYNN", "NNNNYNNNYNYNNYNYYNNNNNNYNNNNYYNNYYNNNNYNNNYY", "NNYNNNNNNNNNYYNNNNNYYNYNNNNNYNYNNYNNYNNNNNYN", "YNYNYNNNNNNNNNNNNNNYYNNYNNNYNNYYNNYYNNNNNNNN", "NNNNNYNNNNYNNNNNYNNNNNNNNNNNYNNNNNNNNNNNNNNN", "NYYYNNNNNNNNNYNNNNNNNNNNNNNNNYYNNNNNNYYYYNYN", "NYNNNYNNYNNNNNYNYNYNYYNNNNNNNNNNNNNNYNNNNNYN", "NNNNNNNNNNNNNNNNYNNNNNNNNNNNYNNNNNYNYYNNNYNN", "NNYNNNYNNNNNNNNNNYNNNNYNNYNNYNNYNNNNNNNNNNNN", "NNYNYYYNNYNNNNNNNNNYNNNNNYYYNNNYNYNNNYNNYNYY", "NNNNYNNNNNYNNNNNNNNYYYNNNNNNNNNYNYYNNNNNNYNN", "NNNNYYNNNNNNNNNNNNYNNYNNNNYNNNNNYNYYNNNNNYNN", "NNYNYYNNYNYYNNNNNNNYYNNNNNNNYNNNNNYNYNNYNNNN", "YNNNNNNNNNNNYNNNNNNNYYNNNNNNNNNYNYNNNNNYYNNY", "NNYNNNNNNNYNNNNYNNNNNNNYNNNYNNNYYNNNNNNYNNNN", "NNNNNNYYNNNNNYYNYNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNYYNNYYNNYNNNYNYYNNNYYNNYYYNNYNNNNNNNNNNNYN", "YNNNNNNNNNYNNNYYNYNNYNNYNNNNNNNNNNNNYNNNNYNN", "YNNYNNYNNNNNYNNNNNNNYNNYNNNNYNYNNNNYNNNNNNYY", "NNYNNYNYNNNNNNNNNNYNNYYNYYNNNNNNNNNNNYNNYNYY", "NNNNNNNNNNNNNNNNNNNNNNNYNNNNNYNNYYYNNNNYNNNN", "YNNNYNNNNNNNYYNNNNNNYNNYNNNYNNYYNNNNYNNNNNNY", "YNNYNNNNNNNNNYNYNNNNYNNNNNNNNNNNNNNNNNYNYNNY", "NNNYNNNYNNNNNYNNNNYNYNNNNYNNYNYYNNYNNNYNNNNN", "NYNNYYYNYNNYYNNNYNNNNNYNNNNYNNNNNNNNYNNNNYNN", "YYNNNYNNNYNNNNNNNNNNNNNNYNNNNNYNNNNYNNNYNNNN", "NYYNNNYYNYNNNNNNNNNNYNYNNYNYNYNNNNYNNNNNNYNN", "NNYNNNNYNNNNYYYNNYYNNNNNNYNYNNNNNNNNNNNNNNNY", "YYNYYYNNNNNNNNNYNNYNNNNNYNNNNNNNNNYNYYNNNNNN", "NNYNNYYNNNNNNYYNNYNNNNNNYNNNNNNNNNNNNNNNYYNN", "NNNNYNNYNNNYNNYYYNNNNNNNYNNYNNYNYNNNNNNNNNYN", "YNNNNNNYNNNNNNNYNNNNNNYNNNNNNYNNNNNNNYNYNNNN", "NYNNNNYNNNYYNNNNYNNNNYNNNYNNYNNNYNNNNNNNNNNN", "NNYNNNNNNYNYNYNNNNNNNNNYNNNNNNNNYNNYNNNNNNNN", "YNNNYYNNNYNNNNNNNNNNNNNNNNYYNNNNNNNNNNNNNYYN", "YNNNNNNNNYNNNNNNYYYNNNNNYNNNNYNNNNNYNNNNNYNN", "NNNNYNNNNYNNNYNNNYNNNNNYNNYNNNNNNYNNNNNNNNNY", "NNNNYNNNNNNYNNYYNNNNNYNNNNNNYNYNNYNNNNYYNNNN", "NYNNNYYNNYYNNYNNNNNNYNYYNNNNNNNNNNYNNNYNNNNN", "NNNNNYNNNNNNNYNNNYNNNNYYNYYNNNNYNNNNNNNNYNNN"}	;

        //test
        int score = this.friendScore.highestScore(friends);

        //verify
        assertEquals(score, 43);
    }

    @Test
    public void testHighestScore_SystemTest2() throws Exception {
        //setup
        String[] friends =
                {"NNNNNNNNNYNNNNNNNNYNNNNYNNNYNYYNNNNYNNNYNNNNNNNNNN", "NNYNYNNNYNNNNNNNNNYNNYNYNNNNYNNNNYNNNNNYYYYNYYYNNN", "NYNNNNNNNNNYYNYNYNNYNNYNNNYNYYNYYNYYNYNYNNNNNNNNNN", "NNNNYNNNNNYNYNNNNYNNNNNNYNNNNYYNNNNYNNNNNNNNYNNNYN", "NYNYNNNNNNNYNNNYYYNNNYNNYNNNYYNNNNNNYYYNYNNNYNYNNN", "NNNNNNYNNNNNNNNYNYNNYNNNYNNYNNYYYNNYNNNNNNNNNNYNNY", "NNNNNYNNNNNNNNNNNNYNNNNYNNNNNYYNNNNYNYNNNNNNNYNNNY", "NNNNNNNNNNNYYNNNNNNYYYNNNNNNNNYNNNNNNNNNNYNYNNNYNN", "NYNNNNNNNYNNYYYNYYNNNNNYNNYNNNYNNNNNNNNNYNNNNNNYYN", "YNNNNNNNYNNNYNNNNYNNNYNNNNYNNNNYNNYNNNNYNNNNYNNNNN", "NNNYNNNNNNNNNYNYYYNNNNYNNNNYNYNNNNYYNYYYNNYNNNNNYN", "NNYNYNNYNNNNNNNNNNNNNNNNNNNNYNNNNNNNYYNNNNYNNNYNNN", "NNYYNNNYYYNNNNNYNNNNYNNYNNNNYNNNNYNNYYNYYNNNNNNNNY", "NNNNNNNNYNYNNNNYNYNNNNNNNNNNNNYNNNYNNNNNYNNNNYNNYN", "NNYNNNNNYNNNNNNNNNNNNNYNNNYNNNNNYNNNNNYYNNNNNNNNNY", "NNNNYYNNNNYNYYNNNYNNNNNNNNYNNYYNNNNYNNNNYNNNYNNNNY", "NNYNYNNNYNYNNNNNNNYNYNYYYYNNNNNNYNYNNNNYNNYNNNYNYY", "NNNYYYNNYYYNNYNYNNNNNNNYNNYYYNNNNYNNYNNYNYYNNYNNNY", "YYNNNNYNNNNNNNNNYNNNNNNNNNNNNNNYNNNNYNNYYNYNNNNNNN", "NNYNNNNYNNNNNNNNNNNNNYNNYNNNNNYNNNNNYNNNNNNYNYNNNN", "NNNNNYNYNNNNYNNNYNNNNNYYYNNNYNNNNYNNYNNNNNNNNYNNNN", "NYNNYNNYNYNNNNNNNNNYNNNYNNNNNNNNNNYNNNNNYNYNYNYNYY", "NNYNNNNNNNYNNNYNYNNNYNNYNYNNNNNNNNNNNNNYNNYYNYNNNN", "YYNNNNYNYNNNYNNNYYNNYYYNNNNNNYNNNNNNNNNYNNYYNYNNNN", "NNNYYYNNNNNNNNNNYNNYYNNNNNNNYNNYYNYNNYNNNYYYNNNNNN", "NNNNNNNNNNNNNNNNYNNNNNYNNNYNNNNNNNNNYNYNNNNNYYNNNY", "NNYNNNNNYYNNNNYYNYNNNNNNNYNNYNNNNNNNNNNNNYNNNNYNNN", "YNNNNYNNNNYNNNNNNYNNNNNNNNNNNNNNNYNYYYNNNYNNYYNYNN", "NYYNYNNNNNNYYNNNNYNNYNNNYNYNNYNNYNNNNYNNNYNYNNNNNY", "YNYYYNYNNNYNNNNYNNNNNNNYNNNNYNYNNNNNNNNNNYNNNNYNNN", "YNNYNYYYYNNNNYNYNNNYNNNNNNNNNYNNYYNYNNYNYNNNNNNNYN", "NNYNNYNNNYNNNNNNNNYNNNNNYNNNNNNNNYNYNNYNYNYNNNNYNN", "NNYNNYNNNNNNNNYNYNNNNNNNYNNNYNYNNNNYNNNYNNNYNYNYNN", "NYNNNNNNNNNNYNNNNYNNYNNNNNNYNNYYNNNNNNNNNNNNNNYNNY", "NNYNNNNNNYYNNYNNYNNNNYNNYNNNNNNNNNNNYYNNYYNNNNNYYY", "YNYYNYYNNNYNNNNYNNNNNNNNNNNYNNYYYNNNNYYNNNYYYNNNNY", "NNNNYNNNNNNYYNNNNYYYYNNNNYNYNNNNNNYNNYNYNNNNYNYNNN", "NNYNYNYNNNYYYNNNNNNNNNNNYNNYYNNNNNYYYNNNNNNNNNNNNN", "NNNNYNNNNNYNNNYNNNNNNNNNNYNNNNYYNNNYNNNYYNNYNNNYYY", "YYYNNNNNNYYNYNYNYYYNNNYYNNNNNNNNYNNNYNYNNNNNNYNNNY", "NYNNYNNNYNNNYYNYNNYNNYNNNNNNNNYYNNYNNNYNNYNNNNNNNY", "NYNNNNNYNNNNNNNNNYNNNNNNYNYYYYNNNNYNNNNNYNYYYYNNYN", "NYNNNNNNNNYYNNNNYYYNNYYYYNNNNNNYNNNYNNNNNYNYYNNYNN", "NNNNNNNYNNNNNNNNNNNYNNYYYNNNYNNNYNNYNNYNNYYNNYNNNN", "NYNYYNNNNYNNNNNYNNNNNYNNNYNYNNNNNNNYYNNNNYYNNNNNNN", "NYNNNNYNNNNNNYNNNYNYYNYYNYNYNNNNYNNNNNNYNYNYNNNNNN", "NYNNYYNNNNNYNNNNYNNNNYNNNNYNNYNNNYNNYNNNNNNNNNNNNY", "NNNNNNNYYNNNNNNNNNNNNNNNNNNYNNNYYNYNNNYNNNYNNNNNNN", "NNNYNNNNYNYNNYNNYNNNNYNNNNNNNNYNNNYNNNYNNYNNNNNNNN", "NNNNNYYNNNNNYNYYYYNNNYNNNYNNYNNNNYYYNNYYYNNNNNYNNN"}	;

        //test
        int score = this.friendScore.highestScore(friends);

        //verify
        assertEquals(score, 49);
    }

}