package com.example.topcoder.graph;

import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import static org.testng.Assert.*;

/*
 * Created by AdelaSarca
 * Date: 11/22/2019
 */
public class ImportsListTest {

    private ImportsList importsList;

    @BeforeMethod
    public void setup() {
        this.importsList = new ImportsList();
    }

    @Test
    public void testImportsCount0() {
        //setup
        String[] requires = new String[]{
                "NNN",
                "NNN",
                "NNN"};
        int[] expected = new int[]{0,0,0};

        //test
        int[] imports = this.importsList.importsCount(requires);

        //verify
        assertEquals(imports, expected);
    }

    @Test
    public void testImportsCount1() {
        //setup
        String[] requires = new String[]{
                "NYYY"
                ,"NNYY"
                ,"NNNY"
                ,"NNNN"};
        int[] expected = new int[]{1, 1, 1, 0};

        //test
        int[] imports = this.importsList.importsCount(requires);

        //verify
        assertEquals(imports, expected);
    }

    @Test
    public void testImportsCount2() {
        //setup
        String[] requires = new String[]{
                "NNNNY"
                ,"NNNNY"
                ,"YNNNY"
                ,"NNNNN"
                ,"NNNNN"};
        int[] expected = new int[]{1, 1, 1, 0, 0};

        //test
        int[] imports = this.importsList.importsCount(requires);

        //verify
        assertEquals(imports, expected);
    }

    @Test
    public void testImportsCount3() {
        //setup
        String[] requires = new String[]{
                "NYYNYNYYYNYYNYNN"
                ,"NNNNNNNNNNNNNNNN"
                ,"NNNNNNNNNNYNNNNN"
                ,"NNNNNNNNNYNNYNNN"
                ,"NYNNNNYNNNYYNNNN"
                ,"NYNNYNYNYNYYNNNN"
                ,"NNNNNNNNNNYNNNNN"
                ,"NNYNNNYNYNYNNNNN"
                ,"NNNNNNYNNNYNNNNN"
                ,"NNNNNNNNNNNNYNNN"
                ,"NNNNNNNNNNNNNNNN"
                ,"NNNNNNNNNNNNNNNN"
                ,"NNNNNNNNNNNNNNNN"
                ,"NNNNNNYNNNYNNNNN"
                ,"YYYYYNYYYYYYYYNY"
                ,"NYYYNNYNNYYNYYNN"};
        int[] expected = new int[]{3, 0, 1, 1, 3, 2, 1, 2, 1, 1, 0, 0, 0, 1, 2, 4};

        //test
        int[] imports = this.importsList.importsCount(requires);

        //verify
        assertEquals(imports, expected);
    }

    @Test
    public void testImportsCount4() {
        //setup
        String[] requires = new String[]{
                "NNNNNYNNNYNYNNNNNNNNNYNNNYYNNNNNNNNNN", "YNNNNYNNYYNYYYYNNNYNNYNNNYYNNNNYYNNNY", "YYNNYYYNYYYYYYYNYNYNYYYYNYYNYNYYYNYNY", "YYYNYYYYYYYYYYYYYNYYYYYYYYYNYYYYYYYYY", "YYNNNYNNYYNYYYYNYNYNNYNNNYYNNNNYYNNNY", "NNNNNNNNNYNYNNNNNNNNNNNNNYYNNNNNNNNNN", "YYNNYYNNYYYYYYYNYNYNNYYYNYYNYNYYYNYNY", "YYYNYYYNYYYYYYYYYNYNYYYYNYYNYNYYYNYYY", "YNNNNYNNNYNYNNNNNNYNNYNNNYYNNNNNNNNNN", "NNNNNNNNNNNYNNNNNNNNNNNNNYNNNNNNNNNNN", "YYNNYYNNYYNYYYYNYNYNNYNNNYYNNNNYYNNNY", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "YNNNNYNNYYNYNNNNNNYNNYNNNYYNNNNNNNNNN", "YNNNNYNNYYNYYNYNNNYNNYNNNYYNNNNNYNNNY", "YNNNNYNNYYNYYNNNNNYNNYNNNYYNNNNNNNNNY", "YYYNYYYNYYYYYYYNYNYNYYYYNYYNYNYYYNYNY", "YNNNNYNNYYNYYYYNNNYNNYNNNYYNNNNYYNNNY", "YYYYYYYYYYYYYYYYYNYYYYYYYYYYYYYYYYYYY", "NNNNNNNNNYNYNNNNNNNNNYNNNYYNNNNNNNNNN", "YYYNYYYYYYYYYYYYYNYNYYYYNYYNYNYYYNYYY", "YYNNYYYNYYYYYYYNYNYNNYYYNYYNYNYYYNYNY", "NNNNNNNNNYNYNNNNNNNNNNNNNYNNNNNNNNNNN", "YYNNYYNNYYYYYYYNYNYNNYNYNYYNNNNYYNNNY", "YYNNYYNNYYYYYYYNYNYNNYNNNYYNNNNYYNNNY", "YYYNYYYNYYYYYYYYYNYNYYYYNYYNYNYYYNYNY", "NNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNYNYNNNNNNNNNNNNNYNNNNNNNNNNN", "YYYYYYYYYYYYYYYYYNYYYYYYYYYNYYYYYYYYY", "YYNNYYNNYYYYYYYNYNYNNYNYNYYNNNNYYNNNY", "YYYNYYYYYYYYYYYYYNYYYYYYYYYNYNYYYYYYY", "YYNNYYNNYYYYYYYNYNYNNYYYNYYNYNNYYNNNY", "YNNNNYNNYYNYYYYNNNYNNYNNNYYNNNNNYNNNY", "YNNNNYNNYYNYYNNNNNYNNYNNNYYNNNNNNNNNY", "YYYNYYYYYYYYYYYYYNYNYYYYYYYNYNYYYNYYY", "YYNNYYNNYYYYYYYNYNYNNYYYNYYNYNYYYNNNY", "YYYNYYYNYYYYYYYNYNYNYYYYNYYNYNYYYNYNY", "YNNNNYNNYYNYYNNNNNYNNYNNNYYNNNNNNNNNN"};
        int[] expected = new int[]{2, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 0, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 1, 1, 1};

        //test
        int[] imports = this.importsList.importsCount(requires);

        //verify
        assertEquals(imports, expected);
    }

    @Test
    public void testImportsCount5() {
        //setup
        String[] requires = new String[]{
                "NNNNNNNNNNNNYNNNNNNNNNNNNNNNYNYYNYNYNNN", "NNNNNYNNNNNNYNNNNNYNNNNNNNNNNNNNNNNNNNN", "NYNNYYNNNNNNYNNNYYYNNNNNNNNNNNNNNNNNNNY", "NYYNYYNYNYNNYNNNYYYNYNNNNNNNNNYNNYNNNYY", "NNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNN", "NNNNNYNNNYNNNNNNNNYNNNNNNNNNNNYNNYNNNYN", "NYYNYYNYNYNNYNNNYYYNYNNNNYNNNNYYNYNYNYY", "NNNNNYNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNYN", "NYYNYYNYNYNNYNNNYYYNYNNNNNYNNNYNNYNNNYY", "NYYNYYNNNNNNYNNNYYYNYNNNNNNNNNNNNNNNNNY", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "YYYNYYNYNYNNYNYYYYYNYYNYNYYYYNYYYYNYYYY", "NNNNNYNYNYNNNNNNNNYNNNNNNNNNNNYNNYNNNYN", "NYYNYYNYNYNNYNYNYYYNYNNNNNYNNNYNYYNYNYY", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNYNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNYNNNNNNNNNNNYYNNNNNNNNNNNNNNNNNNNYN", "NYYNYYNNNNNNYNNNYYYNNNNNNNNNNNNNNNNNNNY", "YYYNYYNNNYNNYNNNYYYNYNNNNYNNYNYYNYNYNYY", "NNNNYNNNNNNNNNNNYYNYNNNNNNNNNNYNNNNYNYN", "YYNNNYNNNNNNYNNNNNYNNNNNNNNNYNYYNYNYYYN", "NNNNYNYNNNNNNNNNYYYNNNNNNNNNNNNNNNNNNNY", "NYYNYYNNNYNNYNNNYYYNYNNNNNNNNNYNNNNNNYY", "NNNNNYNYNYNNNNNNNNYNNNNNNNNNNNYNNYNNNYN", "YYYNYYNYNYNNYNYYYYYNYNNNNNYNYNYYYYNYYYY", "NNNNNNNNNNNNYNNNNNNNNNNNNNNNNNYYNNNYNNN", "YYYNYYNNNNNNYNNNYYYNNNNYNNNNYNYYNYNYYYY", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNYNNNNNNNNNNNNNNNNNYNNNNYNNN", "NYYNYYNYNYNNYNYNYYYNYNNNNNYNNNYNNYNNNYY", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNN", "NNNNYYYNNYNNNNNNYYYNNNNNYNNNNNNNNNNNNYY", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNNNN", "NNNNNYNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN"};
        int[] expected = new int[]{2, 2, 3, 2, 1, 1, 1, 2, 3, 2, 2, 1, 0, 3, 1, 2, 0, 1, 0, 2, 1, 2, 2, 4, 4, 3, 1, 3, 1, 2, 0, 2, 3, 1, 2, 1, 1, 0, 0};

        //test
        int[] imports = this.importsList.importsCount(requires);

        //verify
        assertEquals(imports, expected);
    }

    @Test
    public void testImportsCount6() {
        //setup
        String[] requires = new String[]{
                "NNYNNNNYYYYNNNYNNYYNNYYYNYNNYNNYNNYYNNYNYNNYYYYYYN", "NNNNNNNNNYNNNNNNNYNNNNNYNNNNYNNNNNYNNNNNYNNYNYNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "YYYNYYNYYYYNNNYNNYYNNYYYNYNYYYNYNNYYNNYNYNNYYYYYYN", "NNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNYNNNNNYNNNNNNNNN", "NYYNNNNYYYYNNNYNNYYNNYNYNNNNYYNNNNYYNNNNYNNYYYYYNN", "YYYNYNNYYYYNYYYNNYYNNYYYYYNYYNNYNNYYNYYNYNYYYYYYYN", "NNNNNNNNNNNNNNNNNYNNNNNNNNNNYNNNNNNYNNNNNNNNNNYNNN", "NNYNNNNNNYNNNNYNNYNNNYNYNNNNYNNNNNYYNNNNYNNYYYYYNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNN", "NYYNNNNNNYNNNNYNNYNNNNNYNNNNYNNNNNYNNNNNYNNYYYNYNN", "NYYNYNNNNYYNNNYNNYNNNNNYNNNYYNNYNNYNNNYNYNYYNYNYNN", "NYYNNNNNNYNNNNYNNYNNNNNYNNNNYNNYNNYNNNNNYNNYYYNYNN", "NNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNYNNNNNYYNNNNYNNYNNNYNYNNNNYYNNNNYYNNNNYNNYYYYYNN", "NYYNNNNNYYYNNNYNNYNNNYNYNNNNYNNYNNYYNNYNYNYYYYYYNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNYNNNNNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYNN", "YYYYYYYYYYYNYYYNNYYNYYYYYYYYYYNYYNYYYYYYYNYYYYYYYN", "NYYNNNNNNYYNNNYNNYYNNNNYNNNNYNNYNNYYNYNYYNYYYYYYNN", "NNYNNNNNNYNNNNYNNYNNNNNYNNNNYNNNNNYNNNNNYNNYYYNYNN", "NNYNNNNNNYNNNNYNNYNNNYNYNNNNYNNNNNYNNNNNYNNYYYNYYN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NYYNYNNNNYYNYYYNNYYNNNNYNNNYYNNYNNYYNYYNYNYYYYYYNN", "NNYNNNNYNYYNNNYNNYYNNNNNNNNNYNNYNNYYNNNNNNNNYYYYNN", "NYYNYNNYNYYNNYYNNYYNNYYYNYNNYNNYYNYYNNNNYNYYYYYYYN", "NNYNYNNNNNNNNNYNNYNNNNNNNNNNYNNYNNYNNNYNYNNNNNNYNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNYNNNNNYYNNNNYNNYNNNYNYNNNNYNNNNNYYNNNNYNNYYYYYNN", "YYYYYYNYYYYNYYYNNYYNNYYYYYNYYYNYYYYYNYYNYNYYYYYYYN", "NNYNNNNNNNNNNNYNNYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NYYNYNNYNYYNNNYNNYYNNYYYNYNNYNNYNNYYNNNNYNYYYYYYYN", "NYYNYNNYYYYNYYYNNYYNNYYYYYNYYYNYYNYYNYYNYNYYYYYYYN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNYNNNNNNNNNNYNNNNNNNNNNNNNNNNNNNNN", "YYYYYYNYYYYNYYYNNYYNNYYYNYYYYYNYYNYYNYYNYNYYYYYYYN", "NNNNNNNNNNYNNNNNNYYNNNNNNNNNYNNNNNNYNNNNNNNNNNNYNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNYNNNNNNNNNNNNYNN", "NNYNNNNNNYNNNNYNNYNNNNNYNNNNYNNNNNYNNNNNYNNYYYYYNN", "NNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNNNYNNNNNNNNNNNNNNN", "YNYNNNNYYYYNNNYYNYYNNYYYNYNNYYNYNNYYNNYNYNNYYYYYYN", "NYYNNNNNNYYNNNYNNYNNNNNYNNNNYNNYNNYNNNNNYNNYNYNYNN", "NNNNNNNNNYNNNNNNNYNNNNNYNNNNYNNNNNYNNNNNYNNNNYNNNN", "NNYNNNNNNYNNNNYNNYNNNNNNNNNNNNNNNNYNNNNNNNNNNNNYNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNYNNNNNYNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN", "NNYNNNNNNYNNNNYNNYNNNYNYNNNNYNNNNNYNNNNNYNNYYYNYNN", "NYYNYNNYNYYNNNYNNYYNNYYYNYNNYNNYNNYYNNNNYNNYYYYYYN"};
        int[] expected = new int[]{4, 1, 0, 3, 1, 4, 2, 2, 3, 0, 2, 2, 2, 3, 1, 1, 3, 0, 1, 3, 3, 2, 1, 0, 4, 5, 2, 3, 0, 1, 2, 2, 4, 3, 0, 2, 4, 2, 3, 3, 2, 2, 3, 4, 5, 2, 0, 0, 1, 4};

        //test
        int[] imports = this.importsList.importsCount(requires);

        //verify
        assertEquals(imports, expected);
    }
}